import fs from "node:fs";
import path from "node:path";

const dirs_to_barrel = [
	{
		src_dir: "src/core",
		dist_file: "src/core/index.js",
		ext: ".js",
	},
	{
		src_dir: "src/vite-plugin",
		dist_file: "src/vite-plugin/index.js",
		ext: ".js",
	},
	{
		src_dir: "src/types",
		dist_file: "src/types/index.d.ts",
		ext: ".d.ts",
	},
];

for (const { src_dir, dist_file, ext } of dirs_to_barrel) {
	const abs_src = path.resolve(src_dir);
	const abs_dist = path.resolve(dist_file);
	const dist_dir = path.dirname(abs_dist);

	fs.mkdirSync(dist_dir, { recursive: true });

	const files = fs
		.readdirSync(abs_src)
		.filter((f) => f.endsWith(ext))
		.filter((f) => !f.startsWith("index."));

	const lines = files.map((f) => {
		const name = "./" + f.replace(ext, "");
		if (ext === ".d.ts") {
			return `export type * from '${name}${ext}';`;
		} else {
			return `export * from '${name}${ext}';`;
		}
	});
	lines.unshift("/** This file is automatically generated. Do not edit */\n");

	fs.writeFileSync(abs_dist, lines.join("\n") + "\n");
	console.log(`✅ Generated: ${dist_file}`);
}
